 

services:
  authServer:
    image: auth-service:local
    container_name: ps-auth-service
    ports:
      - "8081"
    depends_on:
      - redis
    networks:
      - ps

  redis:
    image: redis:latest
    container_name: ps-redis
    ports:
      - "6379"
    environment:
      - REDIS_PASSWORD=redis_ps
      - REDIS_PORT=6379
      - REDIS_DATABASES=0
    networks:
      - ps

networks:
  ps:
