

services:
  mainServer:
    image: main-server:local
    container_name: ps-main-server
    ports:
      - "8080"
    depends_on:
      - postgres
    networks:
      - ps

  postgres:
    image: postgres:16.2
    container_name: ps-postgres
    ports:
      - "5432"
    environment:
      - PGUSER=postgres
      - PGPASSWORD=123
      - PGDATABASE=eldoc
      - PGHOST=postgreSQL
    networks:
      - ps
    volumes:
      - ./migrations/PostgreSQLInit.sql:/docker-entrypoint-initdb.d/PostgreSQLInit.sql

networks:
  ps: